/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as SIdRouteImport } from './routes/s/$id'
import { Route as OrganizationsCreateRouteImport } from './routes/organizations/create'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardProfileRouteImport } from './routes/dashboard/profile'
import { Route as BillingSuccessRouteImport } from './routes/billing/success'
import { Route as AuthVerifyEmailRouteImport } from './routes/auth.verify-email'
import { Route as AuthSignupRouteImport } from './routes/auth.signup'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as DashboardTeamsIndexRouteImport } from './routes/dashboard/teams/index'
import { Route as DashboardSettingsIndexRouteImport } from './routes/dashboard/settings/index'
import { Route as DashboardSecretsIndexRouteImport } from './routes/dashboard/secrets/index'
import { Route as DashboardSettingsSecurityRouteImport } from './routes/dashboard/settings/security'
import { Route as DashboardSettingsProfileRouteImport } from './routes/dashboard/settings/profile'
import { Route as DashboardSettingsOrganizationRouteImport } from './routes/dashboard/settings/organization'
import { Route as DashboardSettingsBillingRouteImport } from './routes/dashboard/settings/billing'
import { Route as DashboardSettingsApiTokensRouteImport } from './routes/dashboard/settings/api-tokens'
import { Route as DashboardSecretsCreateRouteImport } from './routes/dashboard/secrets/create'
import { Route as DashboardSecretsSecretIdRouteImport } from './routes/dashboard/secrets/$secretId'
import { Route as ApiWebhooksDodoRouteImport } from './routes/api.webhooks.dodo'
import { Route as ApiTrpcSplatRouteImport } from './routes/api.trpc.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api.auth.$'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const SIdRoute = SIdRouteImport.update({
  id: '/s/$id',
  path: '/s/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsCreateRoute = OrganizationsCreateRouteImport.update({
  id: '/organizations/create',
  path: '/organizations/create',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const BillingSuccessRoute = BillingSuccessRouteImport.update({
  id: '/billing/success',
  path: '/billing/success',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/auth/verify-email',
  path: '/auth/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTeamsIndexRoute = DashboardTeamsIndexRouteImport.update({
  id: '/teams/',
  path: '/teams/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsIndexRoute = DashboardSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardSettingsRoute,
} as any)
const DashboardSecretsIndexRoute = DashboardSecretsIndexRouteImport.update({
  id: '/secrets/',
  path: '/secrets/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsSecurityRoute =
  DashboardSettingsSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => DashboardSettingsRoute,
  } as any)
const DashboardSettingsProfileRoute =
  DashboardSettingsProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => DashboardSettingsRoute,
  } as any)
const DashboardSettingsOrganizationRoute =
  DashboardSettingsOrganizationRouteImport.update({
    id: '/organization',
    path: '/organization',
    getParentRoute: () => DashboardSettingsRoute,
  } as any)
const DashboardSettingsBillingRoute =
  DashboardSettingsBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => DashboardSettingsRoute,
  } as any)
const DashboardSettingsApiTokensRoute =
  DashboardSettingsApiTokensRouteImport.update({
    id: '/api-tokens',
    path: '/api-tokens',
    getParentRoute: () => DashboardSettingsRoute,
  } as any)
const DashboardSecretsCreateRoute = DashboardSecretsCreateRouteImport.update({
  id: '/secrets/create',
  path: '/secrets/create',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSecretsSecretIdRoute =
  DashboardSecretsSecretIdRouteImport.update({
    id: '/secrets/$secretId',
    path: '/secrets/$secretId',
    getParentRoute: () => DashboardRoute,
  } as any)
const ApiWebhooksDodoRoute = ApiWebhooksDodoRouteImport.update({
  id: '/api/webhooks/dodo',
  path: '/api/webhooks/dodo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/billing/success': typeof BillingSuccessRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/settings': typeof DashboardSettingsRouteWithChildren
  '/organizations/create': typeof OrganizationsCreateRoute
  '/s/$id': typeof SIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/api/webhooks/dodo': typeof ApiWebhooksDodoRoute
  '/dashboard/secrets/$secretId': typeof DashboardSecretsSecretIdRoute
  '/dashboard/secrets/create': typeof DashboardSecretsCreateRoute
  '/dashboard/settings/api-tokens': typeof DashboardSettingsApiTokensRoute
  '/dashboard/settings/billing': typeof DashboardSettingsBillingRoute
  '/dashboard/settings/organization': typeof DashboardSettingsOrganizationRoute
  '/dashboard/settings/profile': typeof DashboardSettingsProfileRoute
  '/dashboard/settings/security': typeof DashboardSettingsSecurityRoute
  '/dashboard/secrets': typeof DashboardSecretsIndexRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
  '/dashboard/teams': typeof DashboardTeamsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/billing/success': typeof BillingSuccessRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/organizations/create': typeof OrganizationsCreateRoute
  '/s/$id': typeof SIdRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/api/webhooks/dodo': typeof ApiWebhooksDodoRoute
  '/dashboard/secrets/$secretId': typeof DashboardSecretsSecretIdRoute
  '/dashboard/secrets/create': typeof DashboardSecretsCreateRoute
  '/dashboard/settings/api-tokens': typeof DashboardSettingsApiTokensRoute
  '/dashboard/settings/billing': typeof DashboardSettingsBillingRoute
  '/dashboard/settings/organization': typeof DashboardSettingsOrganizationRoute
  '/dashboard/settings/profile': typeof DashboardSettingsProfileRoute
  '/dashboard/settings/security': typeof DashboardSettingsSecurityRoute
  '/dashboard/secrets': typeof DashboardSecretsIndexRoute
  '/dashboard/settings': typeof DashboardSettingsIndexRoute
  '/dashboard/teams': typeof DashboardTeamsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/billing/success': typeof BillingSuccessRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/settings': typeof DashboardSettingsRouteWithChildren
  '/organizations/create': typeof OrganizationsCreateRoute
  '/s/$id': typeof SIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/api/webhooks/dodo': typeof ApiWebhooksDodoRoute
  '/dashboard/secrets/$secretId': typeof DashboardSecretsSecretIdRoute
  '/dashboard/secrets/create': typeof DashboardSecretsCreateRoute
  '/dashboard/settings/api-tokens': typeof DashboardSettingsApiTokensRoute
  '/dashboard/settings/billing': typeof DashboardSettingsBillingRoute
  '/dashboard/settings/organization': typeof DashboardSettingsOrganizationRoute
  '/dashboard/settings/profile': typeof DashboardSettingsProfileRoute
  '/dashboard/settings/security': typeof DashboardSettingsSecurityRoute
  '/dashboard/secrets/': typeof DashboardSecretsIndexRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
  '/dashboard/teams/': typeof DashboardTeamsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/privacy'
    | '/terms'
    | '/auth/login'
    | '/auth/signup'
    | '/auth/verify-email'
    | '/billing/success'
    | '/dashboard/profile'
    | '/dashboard/settings'
    | '/organizations/create'
    | '/s/$id'
    | '/dashboard/'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/api/webhooks/dodo'
    | '/dashboard/secrets/$secretId'
    | '/dashboard/secrets/create'
    | '/dashboard/settings/api-tokens'
    | '/dashboard/settings/billing'
    | '/dashboard/settings/organization'
    | '/dashboard/settings/profile'
    | '/dashboard/settings/security'
    | '/dashboard/secrets'
    | '/dashboard/settings/'
    | '/dashboard/teams'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy'
    | '/terms'
    | '/auth/login'
    | '/auth/signup'
    | '/auth/verify-email'
    | '/billing/success'
    | '/dashboard/profile'
    | '/organizations/create'
    | '/s/$id'
    | '/dashboard'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/api/webhooks/dodo'
    | '/dashboard/secrets/$secretId'
    | '/dashboard/secrets/create'
    | '/dashboard/settings/api-tokens'
    | '/dashboard/settings/billing'
    | '/dashboard/settings/organization'
    | '/dashboard/settings/profile'
    | '/dashboard/settings/security'
    | '/dashboard/secrets'
    | '/dashboard/settings'
    | '/dashboard/teams'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/privacy'
    | '/terms'
    | '/auth/login'
    | '/auth/signup'
    | '/auth/verify-email'
    | '/billing/success'
    | '/dashboard/profile'
    | '/dashboard/settings'
    | '/organizations/create'
    | '/s/$id'
    | '/dashboard/'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/api/webhooks/dodo'
    | '/dashboard/secrets/$secretId'
    | '/dashboard/secrets/create'
    | '/dashboard/settings/api-tokens'
    | '/dashboard/settings/billing'
    | '/dashboard/settings/organization'
    | '/dashboard/settings/profile'
    | '/dashboard/settings/security'
    | '/dashboard/secrets/'
    | '/dashboard/settings/'
    | '/dashboard/teams/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
  BillingSuccessRoute: typeof BillingSuccessRoute
  OrganizationsCreateRoute: typeof OrganizationsCreateRoute
  SIdRoute: typeof SIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
  ApiWebhooksDodoRoute: typeof ApiWebhooksDodoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/s/$id': {
      id: '/s/$id'
      path: '/s/$id'
      fullPath: '/s/$id'
      preLoaderRoute: typeof SIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/create': {
      id: '/organizations/create'
      path: '/organizations/create'
      fullPath: '/organizations/create'
      preLoaderRoute: typeof OrganizationsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/billing/success': {
      id: '/billing/success'
      path: '/billing/success'
      fullPath: '/billing/success'
      preLoaderRoute: typeof BillingSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify-email': {
      id: '/auth/verify-email'
      path: '/auth/verify-email'
      fullPath: '/auth/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/teams/': {
      id: '/dashboard/teams/'
      path: '/teams'
      fullPath: '/dashboard/teams'
      preLoaderRoute: typeof DashboardTeamsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings/': {
      id: '/dashboard/settings/'
      path: '/'
      fullPath: '/dashboard/settings/'
      preLoaderRoute: typeof DashboardSettingsIndexRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/dashboard/secrets/': {
      id: '/dashboard/secrets/'
      path: '/secrets'
      fullPath: '/dashboard/secrets'
      preLoaderRoute: typeof DashboardSecretsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings/security': {
      id: '/dashboard/settings/security'
      path: '/security'
      fullPath: '/dashboard/settings/security'
      preLoaderRoute: typeof DashboardSettingsSecurityRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/dashboard/settings/profile': {
      id: '/dashboard/settings/profile'
      path: '/profile'
      fullPath: '/dashboard/settings/profile'
      preLoaderRoute: typeof DashboardSettingsProfileRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/dashboard/settings/organization': {
      id: '/dashboard/settings/organization'
      path: '/organization'
      fullPath: '/dashboard/settings/organization'
      preLoaderRoute: typeof DashboardSettingsOrganizationRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/dashboard/settings/billing': {
      id: '/dashboard/settings/billing'
      path: '/billing'
      fullPath: '/dashboard/settings/billing'
      preLoaderRoute: typeof DashboardSettingsBillingRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/dashboard/settings/api-tokens': {
      id: '/dashboard/settings/api-tokens'
      path: '/api-tokens'
      fullPath: '/dashboard/settings/api-tokens'
      preLoaderRoute: typeof DashboardSettingsApiTokensRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/dashboard/secrets/create': {
      id: '/dashboard/secrets/create'
      path: '/secrets/create'
      fullPath: '/dashboard/secrets/create'
      preLoaderRoute: typeof DashboardSecretsCreateRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/secrets/$secretId': {
      id: '/dashboard/secrets/$secretId'
      path: '/secrets/$secretId'
      fullPath: '/dashboard/secrets/$secretId'
      preLoaderRoute: typeof DashboardSecretsSecretIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/webhooks/dodo': {
      id: '/api/webhooks/dodo'
      path: '/api/webhooks/dodo'
      fullPath: '/api/webhooks/dodo'
      preLoaderRoute: typeof ApiWebhooksDodoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardSettingsRouteChildren {
  DashboardSettingsApiTokensRoute: typeof DashboardSettingsApiTokensRoute
  DashboardSettingsBillingRoute: typeof DashboardSettingsBillingRoute
  DashboardSettingsOrganizationRoute: typeof DashboardSettingsOrganizationRoute
  DashboardSettingsProfileRoute: typeof DashboardSettingsProfileRoute
  DashboardSettingsSecurityRoute: typeof DashboardSettingsSecurityRoute
  DashboardSettingsIndexRoute: typeof DashboardSettingsIndexRoute
}

const DashboardSettingsRouteChildren: DashboardSettingsRouteChildren = {
  DashboardSettingsApiTokensRoute: DashboardSettingsApiTokensRoute,
  DashboardSettingsBillingRoute: DashboardSettingsBillingRoute,
  DashboardSettingsOrganizationRoute: DashboardSettingsOrganizationRoute,
  DashboardSettingsProfileRoute: DashboardSettingsProfileRoute,
  DashboardSettingsSecurityRoute: DashboardSettingsSecurityRoute,
  DashboardSettingsIndexRoute: DashboardSettingsIndexRoute,
}

const DashboardSettingsRouteWithChildren =
  DashboardSettingsRoute._addFileChildren(DashboardSettingsRouteChildren)

interface DashboardRouteChildren {
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardSettingsRoute: typeof DashboardSettingsRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardSecretsSecretIdRoute: typeof DashboardSecretsSecretIdRoute
  DashboardSecretsCreateRoute: typeof DashboardSecretsCreateRoute
  DashboardSecretsIndexRoute: typeof DashboardSecretsIndexRoute
  DashboardTeamsIndexRoute: typeof DashboardTeamsIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardSettingsRoute: DashboardSettingsRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardSecretsSecretIdRoute: DashboardSecretsSecretIdRoute,
  DashboardSecretsCreateRoute: DashboardSecretsCreateRoute,
  DashboardSecretsIndexRoute: DashboardSecretsIndexRoute,
  DashboardTeamsIndexRoute: DashboardTeamsIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
  BillingSuccessRoute: BillingSuccessRoute,
  OrganizationsCreateRoute: OrganizationsCreateRoute,
  SIdRoute: SIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
  ApiWebhooksDodoRoute: ApiWebhooksDodoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
